<?xml version='1.0' encoding='utf-8'?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <OutputPath>..\..\..\x64\Engine\Packages\Builtin\ForwardRP\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>ArisenEngine.Rendering</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Engine\ArisenEngine.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\AutoBinding\AutoBinding.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Serialization\Serialization\Serialization.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Update="package.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

<PropertyGroup Condition="'$(Configuration)' == 'Debug'"><OutputPath>..\..\..\Projects\VisualStudio\CSharpEngineTest\Outputs\Debug\Packages\Builtin\ForwardRP\</OutputPath></PropertyGroup><PropertyGroup Condition="'$(Configuration)' == 'Release'"><OutputPath>..\..\..\Projects\VisualStudio\CSharpEngineTest\Outputs\Release\Packages\Builtin\ForwardRP\</OutputPath></PropertyGroup></Project>